// snake-react/src/App.js
import './App.css'
import SnakeGrid from 'snake'
import { useCallback, useEffect, useRef, useState } from 'react'

function App ({ gridSize, intervalTime }) {
  const [w, h] = gridSize
  const snakeGame = useRef(new SnakeGrid(w, h))
  const [gameOver, setGameOver] = useState(false)
  const [isStarted, setIsStarted] = useState(false)
  const [restart, setRestart] = useState(false)
  const [grid, setGrid] = useState(() => snakeGame.current.getGrid())
  const interval = useRef(null)
  const foodMoji = snakeGame.current.food && snakeGame.current.food.text

  useEffect(() => {
    snakeGame.current.start()
    setGrid(snakeGame.current.getGrid())
  }, [])

  const updateGrid = () => {
    setGrid(snakeGame.current.getGrid())
  }

  const handleGameOver = useCallback(() => {
    setGameOver(true)
    setIsStarted(false)
    clearInterval(interval.current)
    interval.current = null
    setRestart(true)
  }, [])

  const startGame = useCallback(() => {
    if (restart) {
      snakeGame.current.start()
      updateGrid()
    }
    interval.current = setInterval(() => {
      snakeGame.current.update()
      if (snakeGame.current.gameOver) {
        handleGameOver(interval)
      } else {
        updateGrid()
      }
    }, intervalTime)
  }, [restart, intervalTime, handleGameOver])

  const handleKeydown = useCallback(
    e => {
      if (!isStarted) {
        if (e.key === ' ') {
          startGame()
          setIsStarted(true)
        }
        return
      }

      switch (e.key) {
        case 'ArrowLeft':
          snakeGame.current.snake.switchDirection('LEFT')
          break
        case 'ArrowRight':
          snakeGame.current.snake.switchDirection('RIGHT')
          break
        case 'ArrowDown':
          snakeGame.current.snake.switchDirection('DOWN')
          break
        case 'ArrowUp':
          snakeGame.current.snake.switchDirection('UP')
          break
        default:
          break
      }
    },
    [isStarted, startGame]
  )

  useEffect(() => {
    document.addEventListener('keydown', handleKeydown)
    return () => {
      document.removeEventListener('keydown', handleKeydown)
    }
  }, [handleKeydown])

  return (
    <main>
      <h1>Snake Game</h1>
      <div className='info'>
        {gameOver && <span>Game Over 🎆</span>}
        <span>
          Score : {snakeGame.current.snake ? snakeGame.current.snake.size() : 0}
        </span>
      </div>
      <div
        className='grid'
        style={{
          gridTemplateRows: `repeat(${h},20px)`,
          gridTemplateColumns: `repeat(${w},20px)`
        }}
      >
        {grid.map((row, i) =>
          row.map((cell, j) => {
            return (
              <div
                key={`${i}${j}`}
                className={`
                cell
                ${cell === 1 ? 'snake' : ''} 
                ${cell === 2 ? 'food' : ''}
                ${cell === 3 ? 'head' : ''}
                `}
                data-food={cell === 2 ? foodMoji : ''}
              />
            )
          })
        )}
      </div>
      <div className='toolbar'>
        <button onClick={startGame} disabled={isStarted}>
          Click or Press space to play
        </button>
      </div>
    </main>
  )
}

export default App

// snake-svelte/src/App.svelte
<script>
  import SnakeGrid from "snake";

  export let gridSize;
  export let intervalTime;

  let [w, h] = gridSize;
  let snakeGame = new SnakeGrid(w, h);
  snakeGame.start();

  let gameOver = false;
  let isStarted = false;
  let restart = false;
  let interval;

  $: grid = snakeGame.getGrid();
  $: foodMoji = snakeGame.food && snakeGame.food.text;

  document.addEventListener("keydown", (e) => {
    switch (e.key) {
      case "ArrowLeft":
        snakeGame.snake.switchDirection("LEFT");
        break;
      case "ArrowRight":
        snakeGame.snake.switchDirection("RIGHT");
        break;
      case "ArrowDown":
        snakeGame.snake.switchDirection("DOWN");
        break;
      case "ArrowUp":
        snakeGame.snake.switchDirection("UP");
        break;
      case " ":
        if (!isStarted) {
          startGame();
          isStarted = true;
        }
    }
  });

  function handleGameOver() {
    gameOver = true;
    isStarted = false;
    clearInterval(interval);
    restart = true;
  }

  const startGame = () => {
    if (restart) {
      snakeGame.start();
      snakeGame = snakeGame;
    }

    interval = setInterval(() => {
      snakeGame.update();
      if (snakeGame.gameOver) {
        handleGameOver(interval);
      } else {
        snakeGame = snakeGame;
      }
    }, intervalTime);
  };
</script>

<main>
  <h1>Snake Game</h1>
  <div class="info">
    {#if gameOver}
      <span>Game Over 🎆</span>
    {/if}
    <span>Score : {snakeGame.snake ? snakeGame.snake.size() : 0}</span>
  </div>
  <div
    class="grid"
    style="grid-template-rows: repeat({h},20px);grid-template-columns: repeat({w},20px);"
  >
    {#each grid as row}
      {#each row as cell}
        <div
          class="
            cell 
            {cell === 1 ? 'snake' : ''} 
            {cell === 2 ? 'food' : ''}
            {cell === 3 ? 'head' : ''}
            "
          data-food={cell === 2 ? foodMoji : ""}
        />
      {/each}
    {/each}
  </div>
  <div class="toolbar">
    <button on:click={startGame} disabled={isStarted}>Click or Press space to play</button>
  </div>
</main>

<style>
  main {
    text-align: center;
    margin: 0 auto;
    display: grid;
    place-items: center center;
  }

  h1 {
    color: #ff3c00;
    font-size: 2rem;
  }

  .info {
    font-size: 28px;
    margin-bottom: 1.5rem;
    width: 100%;
  }

  .grid {
    display: grid;
  }

  .cell {
    border: 1px solid rgb(13, 134, 19);
    display: block;
    background: rgb(44, 161, 50);
    position: relative;
  }

  .cell.head::after {
    position: absolute;
    left: 0;
    width: 100%;
    height: 100%;
    content: "";
    background: #e4f121;
    border-color: #e4f121;
    border-radius: 2px;
  }
  .cell.snake::after {
    position: absolute;
    left: 0;
    width: 100%;
    height: 100%;
    content: "";
    background: #fff020;
    border-color: #fff020;
    border-radius: 2px;
  }

  .cell.food::after {
    position: absolute;
    left: 0;
    width: 100%;
    height: 100%;
    content: attr(data-food);
    border-radius: 5px;
  }

  .toolbar {
    padding: 1rem 0;
  }

  button {
    padding: 1rem 2rem;
    background: #257af8;
    color: white;
    font-size: 1.5rem;
    border: none;
  }

  button:disabled {
    opacity: 0.5;
  }
</style>
